// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#ifndef __BINDINGS_EVIL_WORLD_H
#define __BINDINGS_EVIL_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `exploit:evil/malicious`
void exports_exploit_evil_malicious_malicious(uint64_t buffer);

#ifdef __cplusplus
}
#endif
#endif
