// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#include "use_resource.h"
#include <stdlib.h>

// Imported Functions from `resources:creator/create-resource@0.1.0`

__attribute__((__import_module__("resources:creator/create-resource@0.1.0"), __import_name__("[constructor]buffer")))
extern int32_t __wasm_import_resources_creator_create_resource_constructor_buffer(void);

__attribute__((__import_module__("resources:creator/create-resource@0.1.0"), __import_name__("[method]buffer.write")))
extern void __wasm_import_resources_creator_create_resource_method_buffer_write(int32_t, uint8_t *, size_t);

__attribute__((__import_module__("resources:creator/create-resource@0.1.0"), __import_name__("[method]buffer.read")))
extern void __wasm_import_resources_creator_create_resource_method_buffer_read(int32_t, uint8_t *);

// Exported Functions from `resources:creator/operate-buffer@0.1.0`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("resources:creator/create-resource@0.1.0"), __import_name__("[resource-drop]buffer")))
extern void __wasm_import_resources_creator_create_resource_buffer_drop(int32_t handle);

void resources_creator_create_resource_buffer_drop_own(resources_creator_create_resource_own_buffer_t handle) {
  __wasm_import_resources_creator_create_resource_buffer_drop(handle.__handle);
}

resources_creator_create_resource_borrow_buffer_t resources_creator_create_resource_borrow_buffer(resources_creator_create_resource_own_buffer_t arg) {
  return (resources_creator_create_resource_borrow_buffer_t) { arg.__handle };
}

void use_resource_list_u8_free(use_resource_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

// Component Adapters

resources_creator_create_resource_own_buffer_t resources_creator_create_resource_constructor_buffer(void) {
  int32_t ret = __wasm_import_resources_creator_create_resource_constructor_buffer();
  return (resources_creator_create_resource_own_buffer_t) { ret };
}

void resources_creator_create_resource_method_buffer_write(resources_creator_create_resource_borrow_buffer_t self, use_resource_list_u8_t *data) {
  __wasm_import_resources_creator_create_resource_method_buffer_write((self).__handle, (uint8_t *) (*data).ptr, (*data).len);
}

void resources_creator_create_resource_method_buffer_read(resources_creator_create_resource_borrow_buffer_t self, use_resource_list_u8_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_resources_creator_create_resource_method_buffer_read((self).__handle, ptr);
  *ret = (use_resource_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

__attribute__((__export_name__("resources:creator/operate-buffer@0.1.0#modify-buffer")))
void __wasm_export_exports_resources_creator_operate_buffer_modify_buffer(void) {
  exports_resources_creator_operate_buffer_modify_buffer();
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_use_resource(void);
void __component_type_object_force_link_use_resource_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_use_resource();
}
