// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#ifndef __BINDINGS_USE_RESOURCE_H
#define __BINDINGS_USE_RESOURCE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct resources_creator_create_resource_own_buffer_t {
  int32_t __handle;
} resources_creator_create_resource_own_buffer_t;

typedef struct resources_creator_create_resource_borrow_buffer_t {
  int32_t __handle;
} resources_creator_create_resource_borrow_buffer_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} use_resource_list_u8_t;

// Imported Functions from `resources:creator/create-resource@0.1.0`
extern resources_creator_create_resource_own_buffer_t resources_creator_create_resource_constructor_buffer(void);
extern void resources_creator_create_resource_method_buffer_write(resources_creator_create_resource_borrow_buffer_t self, use_resource_list_u8_t *data);
extern void resources_creator_create_resource_method_buffer_read(resources_creator_create_resource_borrow_buffer_t self, use_resource_list_u8_t *ret);

// Exported Functions from `resources:creator/operate-buffer@0.1.0`
void exports_resources_creator_operate_buffer_modify_buffer(void);

// Helper Functions

extern void resources_creator_create_resource_buffer_drop_own(resources_creator_create_resource_own_buffer_t handle);

extern resources_creator_create_resource_borrow_buffer_t resources_creator_create_resource_borrow_buffer(resources_creator_create_resource_own_buffer_t handle);

void use_resource_list_u8_free(use_resource_list_u8_t *ptr);


#ifdef __cplusplus
}
#endif
#endif
