// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#include "evil_world.h"
#include <stdlib.h>

// Exported Functions from `exploit:evil/malicious`

__attribute__((__weak__, __export_name__("cabi_post_exploit:evil/malicious#malicious")))
void __wasm_export_exports_exploit_evil_malicious_malicious_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void evil_world_list_u8_free(evil_world_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

// Component Adapters

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

__attribute__((__export_name__("exploit:evil/malicious#malicious")))
uint8_t * __wasm_export_exports_exploit_evil_malicious_malicious(void) {
  evil_world_list_u8_t ret;
  exports_exploit_evil_malicious_malicious(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_evil_world(void);
void __component_type_object_force_link_evil_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_evil_world();
}
