// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#ifndef __BINDINGS_EVIL_WORLD_H
#define __BINDINGS_EVIL_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct {
  uint8_t *ptr;
  size_t len;
} evil_world_list_u8_t;

// Exported Functions from `exploit:evil/malicious`
void exports_exploit_evil_malicious_malicious(evil_world_list_u8_t *ret);

// Helper Functions

void evil_world_list_u8_free(evil_world_list_u8_t *ptr);


#ifdef __cplusplus
}
#endif
#endif
